export const BackgroundImageList = [{
    src: '/images/default.jpg',
    topColor: '#009ffe',
    subTitle: '只要你肯努力，没有什么是你不能搞砸的'
  }, {
    src: '/images/skyBlue.jpg',
    topColor: '#4395f9',
    subTitle: '等忙完这一阵，就可以接着忙下一阵了'
  },
  {
    src: '/images/rain.jpg',
    topColor: '#393836',
    subTitle: '世上无难事，只要肯放弃'
  },
  {
    src: '/images/sundy.jpg',
    topColor: '#0085e5',
    subTitle: '假如生活欺骗了你，不要悲伤，不要心急，反正明天也一样'
  },
  {
    src: '/images/zao.png',
    topColor: '#004a89',
    subTitle: '有时候你不努力一下，你都不知道什么叫绝望'
  },
  {
    src: '/images/willNight.jpg',
    topColor: '#b8bab9',
    subTitle: '万事开头难，然后中间难，最后结尾难'
  },
  {
    src: '/images/moreCloud.jpg',
    topColor: '#009ffe',
    subTitle: '今天解决不了的事，不必着急，因为明天还是解决不了'
  }, 
  {
    src: '/images/road.png',
    topColor: '#b8bab9',
    subTitle: '万事开头难，然后中间难，最后结尾难'
  },
  {
    src: '/images/zaoyang.png',
    topColor: '#009ffe',
    subTitle: '今天解决不了的事，不必着急，因为明天还是解决不了'
  },
  {
    src: '/images/yekong.png',
    topColor: '#009ffe',
    subTitle: '今天解决不了的事，不必着急，因为明天还是解决不了'
  },
  {
    src: '/images/xiyang.png',
    topColor: '#b8bab9',
    subTitle: '万事开头难，然后中间难，最后结尾难'
  },
  {
    src: '/images/black.png',
    topColor: '#009ffe',
    subTitle: '今天解决不了的事，不必着急，因为明天还是解决不了'
  },
];

export const lifeStyleList = [{
  "date": "2022-06-10",
  "type": "1",
  "name": "运动指数",
  "level": "1",
  "category": "适宜",
  "text": "天气较好，赶快投身大自然参与户外运动，尽情感受运动的快乐吧。"
}, {
  "date": "2022-06-10",
  "type": "2",
  "name": "洗车指数",
  "level": "4",
  "category": "不宜",
  "text": "不宜洗车，未来24小时内有雨，如果在此期间洗车，雨水和路上的泥水可能会再次弄脏您的爱车。"
}, {
  "date": "2022-06-10",
  "type": "3",
  "name": "穿衣指数",
  "level": "6",
  "category": "热",
  "text": "天气热，建议着短裙、短裤、短薄外套、T恤等夏季服装。"
}, {
  "date": "2022-06-10",
  "type": "4",
  "name": "钓鱼指数",
  "level": "2",
  "category": "较适宜",
  "text": "较适合垂钓，但天气稍热，会对垂钓产生一定的影响。"
}, {
  "date": "2022-06-10",
  "type": "5",
  "name": "紫外线指数",
  "level": "5",
  "category": "很强",
  "text": "紫外线辐射极强，建议涂擦SPF20以上、PA++的防晒护肤品，尽量避免暴露于日光下。"
}, {
  "date": "2022-06-10",
  "type": "6",
  "name": "旅游指数",
  "level": "1",
  "category": "适宜",
  "text": "天气较好，但丝毫不会影响您出行的心情。温度适宜又有微风相伴，适宜旅游。"
}, {
  "date": "2022-06-10",
  "type": "7",
  "name": "过敏指数",
  "level": "2",
  "category": "不易发",
  "text": "天气条件不易诱发过敏，可放心外出，除特殊体质外，无需担心过敏问题。"
}, {
  "date": "2022-06-10",
  "type": "8",
  "name": "舒适度指数",
  "level": "2",
  "category": "较舒适",
  "text": "白天多云，您在这种天气条件下，会感觉早晚凉爽、舒适，午后偏热。"
}, {
  "date": "2022-06-10",
  "type": "9",
  "name": "感冒指数",
  "level": "1",
  "category": "少发",
  "text": "各项气象条件适宜，无明显降温过程，发生感冒机率较低。"
}, {
  "date": "2022-06-10",
  "type": "10",
  "name": "空气污染扩散条件指数",
  "level": "2",
  "category": "良",
  "text": "气象条件对空气污染物稀释、扩散和清除无明显影响，易感人群应适当减少室外活动时间。"
}, {
  "date": "2022-06-10",
  "type": "11",
  "name": "空调开启指数",
  "level": "3",
  "category": "较少开启",
  "text": "您将感到很舒适，一般不需要开启空调。"
}, {
  "date": "2022-06-10",
  "type": "12",
  "name": "太阳镜指数",
  "level": "3",
  "category": "必要",
  "text": "白天太阳辐射较强，建议佩戴透射比1级且标注UV380-UV400的浅色太阳镜"
}, {
  "date": "2022-06-10",
  "type": "13",
  "name": "化妆指数",
  "level": "5",
  "category": "去油",
  "text": "天气较热，建议用露质面霜打底，水质无油粉底霜，透明粉饼，粉质胭脂。"
}, {
  "date": "2022-06-10",
  "type": "14",
  "name": "晾晒指数",
  "level": "2",
  "category": "适宜",
  "text": "天气不错，较适宜晾晒,赶紧把久未见阳光的衣物搬出来吸收一下太阳的味道吧！"
}, {
  "date": "2022-06-10",
  "type": "15",
  "name": "交通指数",
  "level": "1",
  "category": "良好",
  "text": "天气较好，路面干燥，交通气象条件良好，车辆可以正常行驶。"
}, {
  "date": "2022-06-10",
  "type": "16",
  "name": "防晒指数",
  "level": "2",
  "category": "较弱",
  "text": "紫外线强度较弱，建议涂擦SPF在12-15之间，PA+的防晒护肤品。"
}]

export const allCitiesList = {
  cities: [{
    "letter": "B",
    "name": "北京市"
  }, {
    "letter": "T",
    "name": "天津市"
  }, {
    "letter": "S",
    "name": "石家庄市"
  }, {
    "letter": "T",
    "name": "唐山市"
  }, {
    "letter": "Q",
    "name": "秦皇岛市"
  }, {
    "letter": "H",
    "name": "邯郸市"
  }, {
    "letter": "X",
    "name": "邢台市"
  }, {
    "letter": "B",
    "name": "保定市"
  }, {
    "letter": "Z",
    "name": "张家口市"
  }, {
    "letter": "C",
    "name": "承德市"
  }, {
    "letter": "C",
    "name": "沧州市"
  }, {
    "letter": "L",
    "name": "廊坊市"
  }, {
    "letter": "H",
    "name": "衡水市"
  }, {
    "letter": "T",
    "name": "太原市"
  }, {
    "letter": "D",
    "name": "大同市"
  }, {
    "letter": "Y",
    "name": "阳泉市"
  }, {
    "letter": "C",
    "name": "长治市"
  }, {
    "letter": "J",
    "name": "晋城市"
  }, {
    "letter": "S",
    "name": "朔州市"
  }, {
    "letter": "J",
    "name": "晋中市"
  }, {
    "letter": "Y",
    "name": "运城市"
  }, {
    "letter": "X",
    "name": "忻州市"
  }, {
    "letter": "L",
    "name": "临汾市"
  }, {
    "letter": "L",
    "name": "吕梁市"
  }, {
    "letter": "H",
    "name": "呼和浩特市"
  }, {
    "letter": "B",
    "name": "包头市"
  }, {
    "letter": "W",
    "name": "乌海市"
  }, {
    "letter": "C",
    "name": "赤峰市"
  }, {
    "letter": "T",
    "name": "通辽市"
  }, {
    "letter": "E",
    "name": "鄂尔多斯市"
  }, {
    "letter": "H",
    "name": "呼伦贝尔市"
  }, {
    "letter": "B",
    "name": "巴彦淖尔市"
  }, {
    "letter": "W",
    "name": "乌兰察布市"
  }, {
    "letter": "X",
    "name": "兴安盟"
  }, {
    "letter": "X",
    "name": "锡林郭勒盟"
  }, {
    "letter": "A",
    "name": "阿拉善盟"
  }, {
    "letter": "S",
    "name": "沈阳市"
  }, {
    "letter": "D",
    "name": "大连市"
  }, {
    "letter": "A",
    "name": "鞍山市"
  }, {
    "letter": "F",
    "name": "抚顺市"
  }, {
    "letter": "B",
    "name": "本溪市"
  }, {
    "letter": "D",
    "name": "丹东市"
  }, {
    "letter": "J",
    "name": "锦州市"
  }, {
    "letter": "Y",
    "name": "营口市"
  }, {
    "letter": "F",
    "name": "阜新市"
  }, {
    "letter": "L",
    "name": "辽阳市"
  }, {
    "letter": "P",
    "name": "盘锦市"
  }, {
    "letter": "T",
    "name": "铁岭市"
  }, {
    "letter": "C",
    "name": "朝阳市"
  }, {
    "letter": "H",
    "name": "葫芦岛市"
  }, {
    "letter": "Z",
    "name": "长春市"
  }, {
    "letter": "J",
    "name": "吉林市"
  }, {
    "letter": "S",
    "name": "四平市"
  }, {
    "letter": "L",
    "name": "辽源市"
  }, {
    "letter": "T",
    "name": "通化市"
  }, {
    "letter": "B",
    "name": "白山市"
  }, {
    "letter": "S",
    "name": "松原市"
  }, {
    "letter": "B",
    "name": "白城市"
  }, {
    "letter": "Y",
    "name": "延边朝鲜族自治州"
  }, {
    "letter": "H",
    "name": "哈尔滨市"
  }, {
    "letter": "Q",
    "name": "齐齐哈尔市"
  }, {
    "letter": "J",
    "name": "鸡西市"
  }, {
    "letter": "H",
    "name": "鹤岗市"
  }, {
    "letter": "S",
    "name": "双鸭山市"
  }, {
    "letter": "D",
    "name": "大庆市"
  }, {
    "letter": "Y",
    "name": "伊春市"
  }, {
    "letter": "J",
    "name": "佳木斯市"
  }, {
    "letter": "Q",
    "name": "七台河市"
  }, {
    "letter": "M",
    "name": "牡丹江市"
  }, {
    "letter": "H",
    "name": "黑河市"
  }, {
    "letter": "S",
    "name": "绥化市"
  }, {
    "letter": "D",
    "name": "大兴安岭地区"
  }, {
    "letter": "S",
    "name": "上海市"
  }, {
    "letter": "N",
    "name": "南京市"
  }, {
    "letter": "W",
    "name": "无锡市"
  }, {
    "letter": "X",
    "name": "徐州市"
  }, {
    "letter": "C",
    "name": "常州市"
  }, {
    "letter": "S",
    "name": "苏州市"
  }, {
    "letter": "N",
    "name": "南通市"
  }, {
    "letter": "L",
    "name": "连云港市"
  }, {
    "letter": "H",
    "name": "淮安市"
  }, {
    "letter": "Y",
    "name": "盐城市"
  }, {
    "letter": "Y",
    "name": "扬州市"
  }, {
    "letter": "Z",
    "name": "镇江市"
  }, {
    "letter": "T",
    "name": "泰州市"
  }, {
    "letter": "S",
    "name": "宿迁市"
  }, {
    "letter": "H",
    "name": "杭州市"
  }, {
    "letter": "N",
    "name": "宁波市"
  }, {
    "letter": "W",
    "name": "温州市"
  }, {
    "letter": "J",
    "name": "嘉兴市"
  }, {
    "letter": "H",
    "name": "湖州市"
  }, {
    "letter": "S",
    "name": "绍兴市"
  }, {
    "letter": "J",
    "name": "金华市"
  }, {
    "letter": "Q",
    "name": "衢州市"
  }, {
    "letter": "Z",
    "name": "舟山市"
  }, {
    "letter": "T",
    "name": "台州市"
  }, {
    "letter": "L",
    "name": "丽水市"
  }, {
    "letter": "H",
    "name": "合肥市"
  }, {
    "letter": "W",
    "name": "芜湖市"
  }, {
    "letter": "B",
    "name": "蚌埠市"
  }, {
    "letter": "H",
    "name": "淮南市"
  }, {
    "letter": "M",
    "name": "马鞍山市"
  }, {
    "letter": "H",
    "name": "淮北市"
  }, {
    "letter": "T",
    "name": "铜陵市"
  }, {
    "letter": "A",
    "name": "安庆市"
  }, {
    "letter": "H",
    "name": "黄山市"
  }, {
    "letter": "C",
    "name": "滁州市"
  }, {
    "letter": "F",
    "name": "阜阳市"
  }, {
    "letter": "S",
    "name": "宿州市"
  }, {
    "letter": "L",
    "name": "六安市"
  }, {
    "letter": "B",
    "name": "亳州市"
  }, {
    "letter": "C",
    "name": "池州市"
  }, {
    "letter": "X",
    "name": "宣城市"
  }, {
    "letter": "F",
    "name": "福州市"
  }, {
    "letter": "S",
    "name": "厦门市"
  }, {
    "letter": "P",
    "name": "莆田市"
  }, {
    "letter": "S",
    "name": "三明市"
  }, {
    "letter": "Q",
    "name": "泉州市"
  }, {
    "letter": "Z",
    "name": "漳州市"
  }, {
    "letter": "N",
    "name": "南平市"
  }, {
    "letter": "L",
    "name": "龙岩市"
  }, {
    "letter": "N",
    "name": "宁德市"
  }, {
    "letter": "N",
    "name": "南昌市"
  }, {
    "letter": "J",
    "name": "景德镇市"
  }, {
    "letter": "P",
    "name": "萍乡市"
  }, {
    "letter": "J",
    "name": "九江市"
  }, {
    "letter": "X",
    "name": "新余市"
  }, {
    "letter": "Y",
    "name": "鹰潭市"
  }, {
    "letter": "G",
    "name": "赣州市"
  }, {
    "letter": "J",
    "name": "吉安市"
  }, {
    "letter": "Y",
    "name": "宜春市"
  }, {
    "letter": "F",
    "name": "抚州市"
  }, {
    "letter": "S",
    "name": "上饶市"
  }, {
    "letter": "J",
    "name": "济南市"
  }, {
    "letter": "Q",
    "name": "青岛市"
  }, {
    "letter": "Z",
    "name": "淄博市"
  }, {
    "letter": "Z",
    "name": "枣庄市"
  }, {
    "letter": "D",
    "name": "东营市"
  }, {
    "letter": "Y",
    "name": "烟台市"
  }, {
    "letter": "W",
    "name": "潍坊市"
  }, {
    "letter": "J",
    "name": "济宁市"
  }, {
    "letter": "T",
    "name": "泰安市"
  }, {
    "letter": "W",
    "name": "威海市"
  }, {
    "letter": "R",
    "name": "日照市"
  }, {
    "letter": "L",
    "name": "莱芜市"
  }, {
    "letter": "L",
    "name": "临沂市"
  }, {
    "letter": "D",
    "name": "德州市"
  }, {
    "letter": "L",
    "name": "聊城市"
  }, {
    "letter": "B",
    "name": "滨州市"
  }, {
    "letter": "H",
    "name": "菏泽市"
  }, {
    "letter": "Z",
    "name": "郑州市"
  }, {
    "letter": "K",
    "name": "开封市"
  }, {
    "letter": "L",
    "name": "洛阳市"
  }, {
    "letter": "P",
    "name": "平顶山市"
  }, {
    "letter": "A",
    "name": "安阳市"
  }, {
    "letter": "H",
    "name": "鹤壁市"
  }, {
    "letter": "X",
    "name": "新乡市"
  }, {
    "letter": "J",
    "name": "焦作市"
  }, {
    "letter": "P",
    "name": "濮阳市"
  }, {
    "letter": "X",
    "name": "许昌市"
  }, {
    "letter": "L",
    "name": "漯河市"
  }, {
    "letter": "S",
    "name": "三门峡市"
  }, {
    "letter": "N",
    "name": "南阳市"
  }, {
    "letter": "S",
    "name": "商丘市"
  }, {
    "letter": "X",
    "name": "信阳市"
  }, {
    "letter": "Z",
    "name": "周口市"
  }, {
    "letter": "Z",
    "name": "驻马店市"
  }, {
    "letter": "J",
    "name": "济源市"
  }, {
    "letter": "W",
    "name": "武汉市"
  }, {
    "letter": "H",
    "name": "黄石市"
  }, {
    "letter": "S",
    "name": "十堰市"
  }, {
    "letter": "Y",
    "name": "宜昌市"
  }, {
    "letter": "X",
    "name": "襄阳市"
  }, {
    "letter": "E",
    "name": "鄂州市"
  }, {
    "letter": "J",
    "name": "荆门市"
  }, {
    "letter": "X",
    "name": "孝感市"
  }, {
    "letter": "J",
    "name": "荆州市"
  }, {
    "letter": "H",
    "name": "黄冈市"
  }, {
    "letter": "X",
    "name": "咸宁市"
  }, {
    "letter": "S",
    "name": "随州市"
  }, {
    "letter": "E",
    "name": "恩施土家族苗族自治州"
  }, {
    "letter": "X",
    "name": "仙桃市"
  }, {
    "letter": "Q",
    "name": "潜江市"
  }, {
    "letter": "T",
    "name": "天门市"
  }, {
    "letter": "S",
    "name": "神农架林区"
  }, {
    "letter": "C",
    "name": "长沙市"
  }, {
    "letter": "Z",
    "name": "株洲市"
  }, {
    "letter": "X",
    "name": "湘潭市"
  }, {
    "letter": "H",
    "name": "衡阳市"
  }, {
    "letter": "S",
    "name": "邵阳市"
  }, {
    "letter": "Y",
    "name": "岳阳市"
  }, {
    "letter": "C",
    "name": "常德市"
  }, {
    "letter": "Z",
    "name": "张家界市"
  }, {
    "letter": "Y",
    "name": "益阳市"
  }, {
    "letter": "C",
    "name": "郴州市"
  }, {
    "letter": "Y",
    "name": "永州市"
  }, {
    "letter": "H",
    "name": "怀化市"
  }, {
    "letter": "L",
    "name": "娄底市"
  }, {
    "letter": "X",
    "name": "湘西土家族苗族自治州"
  }, {
    "letter": "G",
    "name": "广州市"
  }, {
    "letter": "S",
    "name": "韶关市"
  }, {
    "letter": "S",
    "name": "深圳市"
  }, {
    "letter": "Z",
    "name": "珠海市"
  }, {
    "letter": "S",
    "name": "汕头市"
  }, {
    "letter": "F",
    "name": "佛山市"
  }, {
    "letter": "J",
    "name": "江门市"
  }, {
    "letter": "Z",
    "name": "湛江市"
  }, {
    "letter": "M",
    "name": "茂名市"
  }, {
    "letter": "Z",
    "name": "肇庆市"
  }, {
    "letter": "H",
    "name": "惠州市"
  }, {
    "letter": "M",
    "name": "梅州市"
  }, {
    "letter": "S",
    "name": "汕尾市"
  }, {
    "letter": "H",
    "name": "河源市"
  }, {
    "letter": "Y",
    "name": "阳江市"
  }, {
    "letter": "Q",
    "name": "清远市"
  }, {
    "letter": "D",
    "name": "东莞市"
  }, {
    "letter": "Z",
    "name": "中山市"
  }, {
    "letter": "C",
    "name": "潮州市"
  }, {
    "letter": "J",
    "name": "揭阳市"
  }, {
    "letter": "Y",
    "name": "云浮市"
  }, {
    "letter": "N",
    "name": "南宁市"
  }, {
    "letter": "L",
    "name": "柳州市"
  }, {
    "letter": "G",
    "name": "桂林市"
  }, {
    "letter": "W",
    "name": "梧州市"
  }, {
    "letter": "B",
    "name": "北海市"
  }, {
    "letter": "F",
    "name": "防城港市"
  }, {
    "letter": "Q",
    "name": "钦州市"
  }, {
    "letter": "G",
    "name": "贵港市"
  }, {
    "letter": "Y",
    "name": "玉林市"
  }, {
    "letter": "B",
    "name": "百色市"
  }, {
    "letter": "H",
    "name": "贺州市"
  }, {
    "letter": "H",
    "name": "河池市"
  }, {
    "letter": "L",
    "name": "来宾市"
  }, {
    "letter": "C",
    "name": "崇左市"
  }, {
    "letter": "H",
    "name": "海口市"
  }, {
    "letter": "S",
    "name": "三亚市"
  }, {
    "letter": "S",
    "name": "三沙市"
  }, {
    "letter": "D",
    "name": "儋州市"
  }, {
    "letter": "W",
    "name": "五指山市"
  }, {
    "letter": "Q",
    "name": "琼海市"
  }, {
    "letter": "W",
    "name": "文昌市"
  }, {
    "letter": "W",
    "name": "万宁市"
  }, {
    "letter": "D",
    "name": "东方市"
  }, {
    "letter": "D",
    "name": "定安县"
  }, {
    "letter": "T",
    "name": "屯昌县"
  }, {
    "letter": "C",
    "name": "澄迈县"
  }, {
    "letter": "L",
    "name": "临高县"
  }, {
    "letter": "B",
    "name": "白沙黎族自治县"
  }, {
    "letter": "C",
    "name": "昌江黎族自治县"
  }, {
    "letter": "L",
    "name": "乐东黎族自治县"
  }, {
    "letter": "L",
    "name": "陵水黎族自治县"
  }, {
    "letter": "B",
    "name": "保亭黎族苗族自治县"
  }, {
    "letter": "Q",
    "name": "琼中黎族苗族自治县"
  }, {
    "letter": "C",
    "name": "重庆市"
  }, {
    "letter": "C",
    "name": "成都市"
  }, {
    "letter": "Z",
    "name": "自贡市"
  }, {
    "letter": "P",
    "name": "攀枝花市"
  }, {
    "letter": "L",
    "name": "泸州市"
  }, {
    "letter": "D",
    "name": "德阳市"
  }, {
    "letter": "M",
    "name": "绵阳市"
  }, {
    "letter": "G",
    "name": "广元市"
  }, {
    "letter": "S",
    "name": "遂宁市"
  }, {
    "letter": "N",
    "name": "内江市"
  }, {
    "letter": "L",
    "name": "乐山市"
  }, {
    "letter": "N",
    "name": "南充市"
  }, {
    "letter": "M",
    "name": "眉山市"
  }, {
    "letter": "Y",
    "name": "宜宾市"
  }, {
    "letter": "G",
    "name": "广安市"
  }, {
    "letter": "D",
    "name": "达州市"
  }, {
    "letter": "Y",
    "name": "雅安市"
  }, {
    "letter": "B",
    "name": "巴中市"
  }, {
    "letter": "Z",
    "name": "资阳市"
  }, {
    "letter": "A",
    "name": "阿坝藏族羌族自治州"
  }, {
    "letter": "G",
    "name": "甘孜藏族自治州"
  }, {
    "letter": "L",
    "name": "凉山彝族自治州"
  }, {
    "letter": "G",
    "name": "贵阳市"
  }, {
    "letter": "L",
    "name": "六盘水市"
  }, {
    "letter": "Z",
    "name": "遵义市"
  }, {
    "letter": "A",
    "name": "安顺市"
  }, {
    "letter": "B",
    "name": "毕节市"
  }, {
    "letter": "T",
    "name": "铜仁市"
  }, {
    "letter": "Q",
    "name": "黔西南布依族苗族自治州"
  }, {
    "letter": "Q",
    "name": "黔东南苗族侗族自治州"
  }, {
    "letter": "Q",
    "name": "黔南布依族苗族自治州"
  }, {
    "letter": "K",
    "name": "昆明市"
  }, {
    "letter": "Q",
    "name": "曲靖市"
  }, {
    "letter": "Y",
    "name": "玉溪市"
  }, {
    "letter": "B",
    "name": "保山市"
  }, {
    "letter": "Z",
    "name": "昭通市"
  }, {
    "letter": "L",
    "name": "丽江市"
  }, {
    "letter": "P",
    "name": "普洱市"
  }, {
    "letter": "L",
    "name": "临沧市"
  }, {
    "letter": "C",
    "name": "楚雄彝族自治州"
  }, {
    "letter": "H",
    "name": "红河哈尼族彝族自治州"
  }, {
    "letter": "W",
    "name": "文山壮族苗族自治州"
  }, {
    "letter": "X",
    "name": "西双版纳傣族自治州"
  }, {
    "letter": "D",
    "name": "大理白族自治州"
  }, {
    "letter": "D",
    "name": "德宏傣族景颇族自治州"
  }, {
    "letter": "N",
    "name": "怒江傈僳族自治州"
  }, {
    "letter": "D",
    "name": "迪庆藏族自治州"
  }, {
    "letter": "L",
    "name": "拉萨市"
  }, {
    "letter": "R",
    "name": "日喀则市"
  }, {
    "letter": "C",
    "name": "昌都市"
  }, {
    "letter": "L",
    "name": "林芝市"
  }, {
    "letter": "S",
    "name": "山南市"
  }, {
    "letter": "N",
    "name": "那曲地区"
  }, {
    "letter": "A",
    "name": "阿里地区"
  }, {
    "letter": "X",
    "name": "西安市"
  }, {
    "letter": "T",
    "name": "铜川市"
  }, {
    "letter": "B",
    "name": "宝鸡市"
  }, {
    "letter": "X",
    "name": "咸阳市"
  }, {
    "letter": "W",
    "name": "渭南市"
  }, {
    "letter": "Y",
    "name": "延安市"
  }, {
    "letter": "H",
    "name": "汉中市"
  }, {
    "letter": "Y",
    "name": "榆林市"
  }, {
    "letter": "A",
    "name": "安康市"
  }, {
    "letter": "S",
    "name": "商洛市"
  }, {
    "letter": "L",
    "name": "兰州市"
  }, {
    "letter": "J",
    "name": "嘉峪关市"
  }, {
    "letter": "J",
    "name": "金昌市"
  }, {
    "letter": "B",
    "name": "白银市"
  }, {
    "letter": "T",
    "name": "天水市"
  }, {
    "letter": "W",
    "name": "武威市"
  }, {
    "letter": "Z",
    "name": "张掖市"
  }, {
    "letter": "P",
    "name": "平凉市"
  }, {
    "letter": "J",
    "name": "酒泉市"
  }, {
    "letter": "Q",
    "name": "庆阳市"
  }, {
    "letter": "D",
    "name": "定西市"
  }, {
    "letter": "L",
    "name": "陇南市"
  }, {
    "letter": "L",
    "name": "临夏回族自治州"
  }, {
    "letter": "G",
    "name": "甘南藏族自治州"
  }, {
    "letter": "X",
    "name": "西宁市"
  }, {
    "letter": "H",
    "name": "海东市"
  }, {
    "letter": "H",
    "name": "海北藏族自治州"
  }, {
    "letter": "H",
    "name": "黄南藏族自治州"
  }, {
    "letter": "H",
    "name": "海南藏族自治州"
  }, {
    "letter": "G",
    "name": "果洛藏族自治州"
  }, {
    "letter": "Y",
    "name": "玉树藏族自治州"
  }, {
    "letter": "H",
    "name": "海西蒙古族藏族自治州"
  }, {
    "letter": "Y",
    "name": "银川市"
  }, {
    "letter": "S",
    "name": "石嘴山市"
  }, {
    "letter": "W",
    "name": "吴忠市"
  }, {
    "letter": "G",
    "name": "固原市"
  }, {
    "letter": "Z",
    "name": "中卫市"
  }, {
    "letter": "W",
    "name": "乌鲁木齐市"
  }, {
    "letter": "K",
    "name": "克拉玛依市"
  }, {
    "letter": "T",
    "name": "吐鲁番市"
  }, {
    "letter": "H",
    "name": "哈密市"
  }, {
    "letter": "C",
    "name": "昌吉回族自治州"
  }, {
    "letter": "B",
    "name": "博尔塔拉蒙古自治州"
  }, {
    "letter": "B",
    "name": "巴音郭楞蒙古自治州"
  }, {
    "letter": "A",
    "name": "阿克苏地区"
  }, {
    "letter": "K",
    "name": "克孜勒苏柯尔克孜自治州"
  }, {
    "letter": "K",
    "name": "喀什地区"
  }, {
    "letter": "H",
    "name": "和田地区"
  }, {
    "letter": "Y",
    "name": "伊犁哈萨克自治州"
  }, {
    "letter": "T",
    "name": "塔城地区"
  }, {
    "letter": "A",
    "name": "阿勒泰地区"
  }, {
    "letter": "S",
    "name": "石河子市"
  }, {
    "letter": "A",
    "name": "阿拉尔市"
  }, {
    "letter": "T",
    "name": "图木舒克市"
  }, {
    "letter": "W",
    "name": "五家渠市"
  }, {
    "letter": "B",
    "name": "北屯市"
  }, {
    "letter": "S",
    "name": "双河市"
  }, {
    "letter": "K",
    "name": "可克达拉市"
  }]
}

export const HotCities = ['北京', '上海', '广州', '深圳', '成都', '杭州', '南京', '武汉', '西安', '重庆', '天津', '厦门', '大连', '昆明', '青岛', '长沙']